// <auto-generated />
using System;
using AlainaGarcia_AP1_P2.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlainaGarcia_AP1_P2.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlainaGarcia_AP1_P2.Models.Combos", b =>
                {
                    b.Property<int>("ComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<bool>("Vendido")
                        .HasColumnType("bit");

                    b.HasKey("ComboId");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("AlainaGarcia_AP1_P2.Models.CombosDetalles", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<double>("Costo")
                        .HasColumnType("float");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("DetalleId");

                    b.HasIndex("ComboId");

                    b.HasIndex("ProductoId");

                    b.ToTable("CombosDetalles");
                });

            modelBuilder.Entity("AlainaGarcia_AP1_P2.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<double>("Costo")
                        .HasColumnType("float");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Existencia")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Costo = 4500.0,
                            Descripcion = "Memorio RAM",
                            Existencia = 25,
                            Precio = 5200.0
                        },
                        new
                        {
                            ProductoId = 2,
                            Costo = 4700.0,
                            Descripcion = "Disco Duro",
                            Existencia = 20,
                            Precio = 5450.0
                        },
                        new
                        {
                            ProductoId = 3,
                            Costo = 999.0,
                            Descripcion = "Teclado",
                            Existencia = 25,
                            Precio = 1200.0
                        },
                        new
                        {
                            ProductoId = 4,
                            Costo = 545.0,
                            Descripcion = "Mouse",
                            Existencia = 25,
                            Precio = 850.0
                        });
                });

            modelBuilder.Entity("AlainaGarcia_AP1_P2.Models.CombosDetalles", b =>
                {
                    b.HasOne("AlainaGarcia_AP1_P2.Models.Combos", "Combo")
                        .WithMany("CombosDetalle")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlainaGarcia_AP1_P2.Models.Productos", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AlainaGarcia_AP1_P2.Models.Combos", b =>
                {
                    b.Navigation("CombosDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
